### ISSUE TITLE
Crashes on start with PS4 controller

### ISSUE THREAD

**Issue by dirkwhoffmann** [slembcke/MacControllers#4]
When plugging in my PS4 controller and running the app, I get

"Warning. Oops, didn't find exactly one axis?"

(elements.count was 0 in my case). I'm on highSierra 10.13.4. PS4 controller was plugged in via USB.

**Comment by slembcke** [comment]
Hmm. That's weird, I ripped out the core of this lib to use in other projects and it still works regularly for my PS4 controller. Though I've been avoiding updating to 10.13... Would be interested what is going on there.

However, I don't know if you saw from the main page:
> IMPORTANT! It seems there is a fatal bug in [GCControllerSnapshot snapshotData] that prevents them from being used on OS X 10.11. Until Apple fixes it, this library can only be used on 10.9 or 10.10.

As of 10.12 that bug is still not fixed, and I'm guessing that almost nobody else has ever used GCController on Mac OS X since the actual gamepad hardware is incredibly rare.

I've basically put this project into deep storage, and have all but deleted it from Github. :-\
